### ISSUE TITLE
[1.13.2] Client Crash on loading

### ISSUE THREAD

**Issue by Morpheus1101** [bl4ckscor3/BiomeInfo#1]
[crash-2019-02-16_08.34.42-client.txt](https://github.com/bl4ckscor3/BiomeInfo/files/2871101/crash-2019-02-16_08.34.42-client.txt)

**Comment by bl4ckscor3** [comment]
Hm, so the fix that worked at first didn't work after all. I'll try something different later.

**Comment by bl4ckscor3** [comment]
I was only able to reproduce this with a very specific set of mods loaded in my dev environment. With the changes in edd75bebe3420cbe6c1d3232b68a9e349df80700, the game no longer crashes in that configuration. A new version is up on CurseForge, please let me know whether it works for you or not.
