### ISSUE TITLE
1.20.4 support (Fabric)

### ISSUE THREAD

**Issue by Crystal-Spider** [bl4ckscor3/BiomeInfo#10]
Is a 1.20.4 Fabric version planned?

**Comment by bl4ckscor3** [comment]
It already exists. Although the file on CurseForge was tagged incorrectly, which likely caused it to not show up in launchers. I have fixed that now, and I'm sorry about that mistake.
Modrinth: https://modrinth.com/mod/biomeinfo/version/A66xwrsu
CurseForge: https://curseforge.com/minecraft/mc-mods/biomeinfo-fabric/files/4763019
