### ISSUE TITLE
Backport V1.6 to 1.19.2 forge

### ISSUE THREAD

**Issue by QianFuv** [bl4ckscor3/BiomeInfo#11]
The ability to preset positions is really important! Can you backport?

**Comment by bl4ckscor3** [comment]
Well technically I no longer support 1.19.2, but it should be easy enough to port... Let me see what I can do.

**Comment by QianFuv** [comment]
Thank you for your reply! Hope the process goes smoothly!

**Comment by bl4ckscor3** [comment]
Ok, so it turns out the 1.19.4 files I have uploaded work fine on 1.19.2. I marked them accordingly, so you'll be good to go to use them.

**Comment by QianFuv** [comment]
I apologize for bothering you again! All other functions are working fine at the moment, but once the font size is changed, the text will not display. This could be a small bug that needs to be fixed.
