### ISSUE TITLE
Terralith Biomes not displaying correctly

### ISSUE THREAD

**Issue by Scarlet-Fury** [bl4ckscor3/BiomeInfo#13]
In Forge 47.3.0 and Minecraft 1.20.1, Biome Info fails to display/load Terralith Biomes in the correct format, and instead it pops up like this:

biome.terralith.snowy_badlands

It's not a huge issue, but it does look weird lol

For context, this happens regardless of any other mods installed

![2024-08-13_17 52 41](https://github.com/user-attachments/assets/7cdc3787-cd09-402c-af82-a3ba6b75ae72)

**Comment by bl4ckscor3** [comment]
Looking at the mod file I can see that Terralith doesn't add translations for their biomes, so this is a Terralith bug. If there are no translations, BiomeInfo can only display the internal name.

**Comment by Scarlet-Fury** [comment]
> Looking at the mod file I can see that Terralith doesn't add translations for their biomes, so this is a Terralith bug. If there are no translations, BiomeInfo can only display the internal name.

So by translations do you mean language translations? 

Cause if so, that's interesting that your mod requires that to display them properly, but also interesting that Terralith doesn't have those...

Anyhay, thanks! I'll go ask about it on their page

**Comment by bl4ckscor3** [comment]
Yes, I mean language translations. It's not at all interesting that BiomeInfo needs them, because all things that have human readable names in Minecraft work that way. Without them, the game would not know what the correct words are for the language that the user has selected. You have some language key that is the same across all languages (this is what you see with Terralith's biomes), which is used as a lookup for the actual translation. Vanilla adds these for all its biomes, so you do see the proper names.

**Comment by Scarlet-Fury** [comment]
> Yes, I mean language translations. It's not at all interesting that BiomeInfo needs them, because all things that have human readable names in Minecraft work that way. Without them, the game would not know what the correct words are for the language that the user has selected. You have some language key that is the same across all languages (this is what you see with Terralith's biomes), which is used as a lookup for the actual translation. Vanilla adds these for all its biomes, so you do see the proper names.

Gotcha. I mean it's interesting to me because I'm still very new to developing modpacks and mods for the game, so learning as much as I can about how it works is important heh

As far as other languages go, I guess I'm just so used to English that I didn't even consider that, oops >.<

If the Terralith team never gets back to me or never makes such language translations, do you think there's a way I could do so? I'd just hate to have to remove either mod because of something silly like this >.<

**Comment by bl4ckscor3** [comment]
Yeah, all language files can be modified with resource packs. See the [Minecraft wiki](https://minecraft.wiki/w/Resource_pack#Language) for an explanation. As an example, a language file that properly translates the biome in your screenshot above to English would look like this:
```json
{
	"biome.terralith.snowy_badlands": "Snowy Badlands"
}
```

**Comment by catter1** [comment]
Hi, Terralith dev here. Normally our translations work fine, but I broke something recently. More information on the issue made on the Terralith repo here: https://github.com/Stardust-Labs-MC/Terralith/issues/158#issuecomment-2289347487. If you're too lazy to click/read, the temporary bandaid solution is to install our resourcepack [Sparkles](https://modrinth.com/resourcepack/sparkles), which also has our translations.

Just making the comment so other people can see what's going on if they're curious.
