### ISSUE TITLE
Config just doesn't work?

### ISSUE THREAD

**Issue by Gamershy** [bl4ckscor3/BiomeInfo#14]
So I'm using the latest version of the mod from modrinth, which is r18.
I've tried changing the numerical position values, I've changed the position preset, text alignment, everything. I've restarted the game, reloaded the world, even modified the config file directly, none of the offset values I'm using are applying. Only the text alignment and position preset.
![image](https://github.com/user-attachments/assets/ad36de09-ec71-44ba-823c-a86bb2a60923)
![image](https://github.com/user-attachments/assets/d74d3f05-3ebd-45ff-8e9b-2d69e1921457)

**Comment by Gamershy** [comment]
Nevermind, I figured it out. You have to set the preset to "NONE" for the position configs to work. Really annoying though. Maybe make the numerical positions act as an offset from the preset? So if it's set to "TOP_MIDDLE" and the Y position is set to "20", those add together to make a final position

**Comment by bl4ckscor3** [comment]
That specific approach would change the behavior of existing configs which use a position preset other than NONE.
