### ISSUE TITLE
[1.13.2]  Server Crash on Load

### ISSUE THREAD

**Issue by Morpheus1101** [bl4ckscor3/BiomeInfo#2]
Mod vers: 1.2.2
Forge vers: 25.0.22

[crash-2019-02-17_22.25.59-server.txt](https://github.com/bl4ckscor3/BiomeInfo/files/2872934/crash-2019-02-17_22.25.59-server.txt)

**Comment by bl4ckscor3** [comment]
BiomeInfo is not supposed to be installed on a dedicated server.
