### ISSUE TITLE
Feature request: option to display advanced biome name, add config for position

### ISSUE THREAD

**Issue by calloatti** [bl4ckscor3/BiomeInfo#5]
Now that there are a few new biome mods for Fabric, it would be nice if you could include the mod name to the biome name, for example:

Now: `Dense Woodlands`

Alternative1: `Terrestria: Dense Woodlands`

Alternative2: `terrestria:dense_woodlands`

This could be a config option, or depend on the status of F3+h advanced tooltips.

Also, config for position: Top/Bottom Left/Right, x/y margins would be nice.

**Comment by bl4ckscor3** [comment]
I'm not maintaining the fabric version of this mod.

**Comment by bl4ckscor3** [comment]
Addendum: If someone else wants to pull request these features, they're more than welcome to do that - I will release a new version with those.
