### ISSUE TITLE
No in-game config

### ISSUE THREAD

**Issue by vaindil** [bl4ckscor3/BiomeInfo#6]
I'm running MC 1.14.4, Forge 28.1.26, and BiomeInfo 1.2.4, and there doesn't seem to be any in-game config available despite the CurseForge page saying there should be. The mods menu config button is grayed out, and nothing seems to have been added to my normal options menu.

**Comment by bl4ckscor3** [comment]
Forge for 1.14 does not have a configuration GUI yet. I cannot do anything about this.

**Comment by vaindil** [comment]
I'm also using HWYLA and it has a config menu in the mods menu, is that what you're referring to? Either way, thanks!

**Comment by bl4ckscor3** [comment]
Yes, there are ways around Forge's restriction and it is possible to have a working configuration GUI in the mod list menu, but I'd rather wait for them to implement it properly.

**Comment by vaindil** [comment]
Understood, I was just curious. Thanks again!
