### ISSUE TITLE
Can't this info be centered？

### ISSUE THREAD

**Issue by eoqwq2333** [bl4ckscor3/BiomeInfo#9]
<img width="440" alt="image" src="https://github.com/bl4ckscor3/BiomeInfo/assets/132819541/9da4f263-a267-449c-a3b9-e636725b5e85">
<img width="434" alt="image" src="https://github.com/bl4ckscor3/BiomeInfo/assets/132819541/e6204f77-3789-47d2-9e38-10183de978cc">
<img width="1280" alt="image" src="https://github.com/bl4ckscor3/BiomeInfo/assets/132819541/c861dff2-3110-4f1a-8472-3d67366db529">
Can't this info be centered？
Forge version：1.20.1-Forge-47.1.28

**Comment by bl4ckscor3** [comment]
Not quite sure what you mean. It is centered around the x/y position.

**Comment by eoqwq2333** [comment]
ok
